<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ghostlist.Core\Ghostlist.Core.csproj" />
    <Resource Include="Assets\ghostlist.ico" />
    <EmbeddedResource Include="Localization\*.json" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\ghostlist.ico</ApplicationIcon>
    <AssemblyName>Ghostlist</AssemblyName>
  </PropertyGroup>

</Project>
